### ISSUE TITLE
A question about the setting of the T5 rewriter

### ISSUE THREAD

**Issue by ChuanMeng** [terrierteam/monoQA#1]
Hi,
Thank you for releasing the code for the great work.
I have a question about the setting of the T5 rewrite.
Our paper shows, "we employ another T5 model trained using the CANARD dataset to rewrite the OR-QuAC and OR-CoQA test set questions into context-independent questions that can be used as input for monoQA".

The T5 rewriter here is fed with only **previous utterances** or **previous utterances plus their corresponding answers**?

I look forward to your reply!

**Comment by 9meo** [comment]
Hi,

Thank you for your interest in monoQA.
We use *previous utterances plus their corresponding answers *as the input
for the T5 query rewriting model.

Best wishes,
Sarawoot

**Comment by ChuanMeng** [comment]
Thank you Sarawoot.
I checked the original code and paper of ConvDR and I found ConvDR only used _previous utterances_  on the OR-QuAC dataset. So I was wondering in our paper if we also make ConvDR access the answers for the previous utterances as monoQA did. 

Best wishes,
Chuan

**Comment by 9meo** [comment]
็Hi,

Yes, for the input of ConvDR, we only used *previous utterances. *But for
monoQA, we plan to use it not only for Conversational Question Answering
(multi-turn) but also the single-turn QA too.

"So I was wondering in our paper if we also make ConvDR access the answers
for the previous utterances as monoQA did."
- yes sure, I think you can do that because ConvDR learns to mimic the
manually rewritten utterance, which should benefit from this KD technique
to extract the answer from the passage.

Best wishes,
Sarawoot

**Comment by ChuanMeng** [comment]
Thank you Sarawoot!
